name: Github Actions Demo
on: [push]
jobs:
  Check-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "triggered by ${{ github.event_name }} event"
      - run: echo "running on a ${{ runner.os }} server hosted by Github"
      - name: check out repo code
        uses: actions/checkout@v2
      - run: echo "the ${{ github.resository }} has been cloned"
      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}